mysite/myauth/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from .views import (MyLogoutView,
                    set_cookie_view,
                    get_cookie_view,
                    set_session_view,
                    get_session_view,
                    AboutMeViews,
                    RegisterView,
                    ChangeAvatarUser,
                    UserListView,
                    UserDetailView,
                    UserUpdate,
                    )

app_name = 'myauth'

urlpatterns = [
    path(
        'login/',
        LoginView.as_view(
            template_name="myauth/login.html",
            redirect_authenticated_user=True,
        ),
        name='login'
    ),
    path("logout/", MyLogoutView.as_view(), name="logout"),
    path("cookie/get/", get_cookie_view, name="cookie-get"),
    path("cookie/set/", set_cookie_view, name="cookie-set"),
    path("session/get/", get_session_view, name="session-get"),
    path("session/set/", set_session_view, name="session-set"),
    path("about-me/", AboutMeViews.as_view(), name="about-me"),
    path("register/", RegisterView.as_view(), name="register"),
    path("users/", UserListView.as_view(), name="users-list"),
    path("users/<int:pk>/", UserDetailView.as_view(), name="users-detail"),
    path("change_avatar/<int:pk>/", ChangeAvatarUser.as_view(), name="change-avatar"),

    path("users/update/<int:pk>/", UserUpdate.as_view(), name="users-update"),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from django.contrib.sitemaps.views import sitemap

from .sitemaps import sitemaps

urlpatterns = [
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),

    path('req/', include('requestdataapp.urls')),
    path('accounts/', include('myauth.urls')),
    path('blog/', include('blogapp.urls')),
    path(
        'sitemap.xml',
        sitemap,
        {"sitemaps": sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    )
]

urlpatterns += i18n_patterns(
path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('shop/', include('shopapp.urls')),
)


if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls"))
    )

mysite/shopapp/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import (
    shop_index,
    groups_list,
    ProductListView,
    ProductDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    OrderListView,
    OrderDetailView,
    OrderCreateView,
    OrderDeleteView,
    OrderUpdateView,
    OrdersDataExportView,
    LatestProductsFeed,
    UserOrdersListView,
    OrdersExportView
)

from .api import (
    ProductViewSet,
    OrderViewSet
)


app_name = 'shopapp'

routers = DefaultRouter()
routers.register("products", ProductViewSet)
routers.register("orders", OrderViewSet)

urlpatterns = [
    path('', shop_index, name='index'),
    path('groups/', groups_list, name='groups_list'),
    path('products/', ProductListView.as_view(), name='products_list'),
    path('products/create/', ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('products/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('products/latest/feed/', LatestProductsFeed(), name='produucts_feed'),
    path('orders/', OrderListView.as_view(), name='orders_list'),
    path('orders/<int:pk>/', OrderDetailView.as_view(), name='order_detail'),
    path('orders/neworder/', OrderCreateView.as_view(), name='order_create'),
    path('orders/<int:pk>/delete/', OrderDeleteView.as_view(), name='order_delete'),
    path('orders/<int:pk>/update/', OrderUpdateView.as_view(), name='order_update'),
    path('orders/export/', OrdersDataExportView.as_view(), name='orders_export'),
    path('api/', include(routers.urls)),

    path('users/<int:user_id>/orders/', UserOrdersListView.as_view(), name='user_order'),
    path('users/<int:user_id>/orders/export/', OrdersExportView.as_view(), name='orders_export'),
]

mysite/shopapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _



def product_preview_directory_path(instance: "Product", filename: str) -> str:
    """Определяет место хранения файла картинки-превью"""
    return f"products/product_{instance.pk}/preview/{filename}"


class Product(models.Model):

    class Meta:
        ordering =['name', 'price']
        verbose_name = _('product')
        verbose_name_plural = _('products')

    name = models.CharField(max_length=100)
    description = models.TextField(null=False, blank=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.PositiveSmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT, default=1)
    preview = models.ImageField(null=True, blank=True, upload_to=product_preview_directory_path)


    def __str__(self) -> str:
        return f"Product: pk={self.pk}, name={self.name!r}"

    def get_absolute_url(self):
        return reverse("shopapp:product_detail", kwargs={"pk": self.pk})


def product_images_directory_path(instance: "ProductImage", filename: str) -> str:
    """Определяет место хранения файлов картинок продукта"""
    return f"products/product_{instance.product.pk}/images/{filename}"


class ProductImage(models.Model):
    """Класс для хранения изображений для продуктов"""
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(null=True, blank=True, upload_to=product_images_directory_path)
    description = models.CharField(max_length=200, null=False, blank=True)


class Order(models.Model):
    class Meta:
        verbose_name = _('order')
        verbose_name_plural = _('orders')

    delivery_address = models.TextField(null=False, blank=True)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name='orders')

mysite/shopapp/forms.py
from django import  forms


from .models import Product, Order


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = 'name', 'price', 'description', 'discount', 'preview'



class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = 'delivery_address', 'promocode', 'user', 'products'


class CSVImportForm(forms.Form):
    """Форма для импорта данных."""

    csv_file = forms.FileField()

mysite/shopapp/views.py
import logging
from timeit import default_timer

from django.contrib.auth.models import Group, User
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect, HttpResponseForbidden, JsonResponse
from django.shortcuts import render, reverse
from django.core.cache import cache
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView,View
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin, UserPassesTestMixin
from django.contrib.syndication.views import Feed
from django.shortcuts import get_object_or_404

from .models import Product, Order
from .forms import ProductForm, OrderForm


log = logging.getLogger(__name__)

# Create your views here.
def shop_index(request: HttpRequest)-> render:
    products = [
        ('Laptop', 1999),
        ('Desktop', 2999),
        ('Smartphone', 999),
    ]
    context = {
        'time_running': default_timer(),
        'products': products,
    }
    return render(request, 'shopapp/shop-index.html', context=context)


def groups_list(request: HttpRequest) -> render:
    context = {
        'groups': Group.objects.prefetch_related('permissions').all(),
    }
    return render(request, 'shopapp/groups-list.html', context=context)


class ProductListView(ListView):
    # model = Product
    template_name = 'shopapp/products-list.html'
    context_object_name = 'products'
    queryset = Product.objects.filter(archived=False)


class ProductDetailView(DetailView):
    template_name = 'shopapp/product-details.html'
    # model = Product
    queryset = Product.objects.prefetch_related('images').all()
    context_object_name = 'product'


class ProductCreateView(PermissionRequiredMixin, CreateView):
    """имя файла html шаблона формируется из названия модели (product)  и суффикса  (_form )"""
    permission_required = "shopapp.add_product"
    model = Product
    success_url = reverse_lazy("shopapp:products_list")
    form_class = ProductForm

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


class ProductUpdateView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    permission_required = "shopapp.change_product"
    model = Product
    fields = 'name', 'price', 'description', 'discount', 'preview'
    template_name_suffix = "_update_form"

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.created_by == self.request.user or self.request.user.is_superuser:
            return obj
        return HttpResponseForbidden("Вы не можете редактировать этот продукт.")


    def get_success_url(self):
        log.info("Update product pk: %s", self.object.pk)
        return reverse("shopapp:product_detail", kwargs={"pk": self.object.pk})



class ProductDeleteView(DeleteView):
    """имя файла html шаблона формируется из названия модели (product)  и суффикса  (_confirm_delete )"""
    model = Product
    success_url = reverse_lazy("shopapp:products_list")

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)


class OrderListView(ListView):
    model = Order
    template_name = 'shopapp/orders-list.html'
    context_object_name = 'orders'


class OrderDetailView(PermissionRequiredMixin, DetailView):
    permission_required = "shopapp.view_order"
    template_name = 'shopapp/order-detail.html'
    model = Order
    context_object_name = 'order'


class OrderCreateView(CreateView):
    """имя файла html шаблона формируется из названия модели (order)  и суффикса  (_form )"""
    model = Order
    success_url = reverse_lazy("shopapp:orders_list")
    form_class = OrderForm


class OrderDeleteView(DeleteView):
    """имя файла html шаблона формируется из названия модели (order)  и суффикса  (_confirm_delete )"""
    model = Order
    success_url = reverse_lazy("shopapp:orders_list")

class OrderUpdateView(UpdateView):
    """имя файла html шаблона формируется из названия модели (order)  и суффикса  указанного в параметре template_name_suffix"""
    model = Order
    fields = 'delivery_address', 'promocode', 'user', 'products'
    template_name_suffix = "_update_form"
    # success_url = reverse_lazy("shopapp:products_list")

    def get_success_url(self):
        return reverse("shopapp:order_detail", kwargs={"pk": self.object.pk})


class OrdersDataExportView(UserPassesTestMixin, View):
    def test_func(self):
        return self.request.user.is_staff

    def get(self, request: HttpRequest) -> JsonResponse:
        orders = Order.objects.select_related('user').prefetch_related('products').order_by("pk").all()
        orders_data = [
            {
                "pk": order.pk,
                "delivery_address": order.delivery_address,
                "promocode": order.promocode,
                "user": order.user.pk,
                "products": [product.pk for product in order.products.all()]
            }
            for order in orders
        ]
        return JsonResponse({"orders": orders_data})


# class ProductViewSet(ModelViewSet):
#     queryset = Product.objects.select_related('created_by').prefetch_related('images').all()
#     serializer_class = ProductSerializer
#     filterset_fields = [
#         "name",
#         "description",
#         "price",
#         "discount",
#         "archived",
#     ]
#
#     filter_backends = [
#         SearchFilter,
#         DjangoFilterBackend,
#         OrderingFilter
#     ]
#
#     search_fields = ["name", "description"]
#
#     ordering_fields = [
#         "pk",
#         "name",
#         "price",
#         "discount",
#     ]
#
#     # def get_queryset(self):
#     #     return self.queryset.prefetch_related('images')
#
#
# class OrderViewSet(ModelViewSet):
#     queryset = Order.objects.prefetch_related('products').all()
#     serializer_class = OrderSerializer
#
#     filterset_fields = [
#         "delivery_address",
#         "promocode",
#         "user",
#     ]
#
#     filter_backends = [
#         SearchFilter,
#         DjangoFilterBackend,
#         OrderingFilter
#     ]
#
#     search_fields = ["delivery_address", "user"]
#
#     ordering_fields = [
#         "pk",
#         "promocode",
#         "delivery_address",
#     ]


class LatestProductsFeed(Feed):
    title = "New products(latest)"
    description = "Updates on changes and additions products"
    link = reverse_lazy("shopapp:products_list")

    def items(self):
        return Product.objects.filter(archived=False).order_by("-created_by")[:5]

    def item_title(self, item: Product):
        return item.name

    def item_description(self, item: Product):
        return item.description[:200]


class UserOrdersListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Order
    template_name = 'shopapp/orders_user.html'
    context_object_name = 'orders'


    def get_queryset(self):
        """Получение id user'a по которому производиться запрос"""
        user_id = self.kwargs['user_id']
        self.onwer = get_object_or_404(User, pk=user_id)
        return Order.objects.filter(user=self.onwer).select_related('user').prefetch_related('products').order_by("pk").all()

    def get_context_data(self, **kwargs):
        """Добавление id user'a в контекст шаблона"""
        context = super().get_context_data(**kwargs)
        context['user'] = self.onwer
        return context

    def test_func(self):
        """Просматривать список ордеров могут только суперпользователь, администраторы
            и авторы заказов
        """
        return (self.request.user.is_superuser
                or self.request.user.is_staff
                or self.request.user.pk == self.kwargs['user_id'])



class OrdersExportView(View):
    def get(self, request: HttpRequest, user_id) -> HttpResponse|JsonResponse:
        cache_key = f"user_{user_id}"
        orders_data = cache.get(cache_key)
        if orders_data is None:
            try:
                user = User.objects.get(pk=user_id)
            except:
                return HttpResponse("User not found", status=404)

            orders = Order.objects.filter(user=user).select_related('user').prefetch_related('products').order_by("pk").all()
            orders_data = [
                {
                    "pk": order.pk,
                    "user": order.user.pk,
                    "delivery_address": order.delivery_address,
                    "promocode": order.promocode,
                    "products": [product.pk for product in order.products.all()]
                }
                for order in orders
            ]
            cache.set(cache_key, orders_data, 120)
        return JsonResponse({"orders": orders_data})

mysite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
      {% block title %}
        Base Title
      {% endblock %}
    </title>
</head>
<body>
  {% block body %}
    Base Body
  {% endblock %}

  <div>
    {% now 'H:i' %}
  </div>
  <div>
      {% now 'l' as current_weekday %}
      Today is: {{ current_weekday }}
  </div>
</body>
</html>

mysite/shopapp/templates/shopapp/create-order.html
{% extends 'shopapp/base.html'%}

{% block title %}
  Create order
{% endblock %}


{% block body %}
  <h1>Create new order</h1>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p}}
      <button type="submit">Create</button>
    </form>
  </div>

  <div>
    <a href="{% url 'shopapp:orders_list' %}">Back to orders list </a>
  </div>

{% endblock %}

mysite/shopapp/templates/shopapp/create-product.html
{% extends 'shopapp/base.html'%}

{% block title %}
  Create product
{% endblock %}


{% block body %}
  <h1>Create new product</h1>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p}}
      <button type="submit">Create</button>
    </form>
  </div>

  <div>
    <a href="{% url 'shopapp:products_list' %}"> Back to products list </a>
  </div>

{% endblock %}

mysite/shopapp/templates/shopapp/groups-list.html
{% extends 'shopapp/base.html'%}

{% block title %}
    Groups list
{% endblock %}


{% block body %}
    <h1>Groups:</h1>
    <div>
        {% if not groups %}
            <h3>Not groups  yet </h3>
        {% else %}
            <ul>
                {% for group in groups %}
                    <li>
                        <div>{{ group.name }}</div>
                        <ul>
                            {% for permission in group.permissions.all %}
                                <li>
                                    {{ permission.name }}
                                    (<code>{{ permission.codename }}</code>)
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                {% endfor %}
            </ul>
        {% endif%}
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_confirm_delete.html
{% extends 'shopapp/base.html'%}

{% block title %}
  Delete order {{ object.pk }}
{% endblock %}


{% block body %}
  <h1>Delete order {{ object.pk }}</h1>
  <br>
  <div>
    <a href="{% url 'shopapp:order_detail' pk=object.pk %}"> Back to order </a>
  </div>
  <br>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Delete</button>
    </form>
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_form.html
{% extends 'shopapp/base.html'%}

{% block title %}
  Creeate order
{% endblock %}


{% block body %}
  <h1>Create new order from form</h1>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p}}
      <button type="submit">Create</button>
    </form>
  </div>

<div>
    <a href="{% url 'shopapp:orders_list' %}"> Back to order list </a>
  </div>

{% endblock %}

mysite/shopapp/templates/shopapp/order_update_form.html
{% extends 'shopapp/base.html'%}

{% block title %}
  Form order Update
{% endblock %}


{% block body %}
  <h1>Update order from form</h1>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p}}
      <button type="submit">Update</button>
    </form>
  </div>

<div>
    <a href="{% url 'shopapp:order_detail' pk=object.pk %}"> Back to order {{ object.pk}} </a>
  </div>

{% endblock %}

mysite/shopapp/templates/shopapp/orders_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}
    {% load admin_urls %}
    <li>
        <a href="{% url 'admin:import_orders_csv' %}" class="addlink">Import orders CSV</a>
    </li>
    {{ block.super }}
{% endblock %}

mysite/shopapp/templates/shopapp/orders_user.html
{% extends 'shopapp/base.html'%}
{% load cache %}

{% block title %}
    Orders list for user # {{ user.pk }}
{% endblock %}


{% block body %}
    {% if request.user.is_staff or request.user.is_superuser or user.pk == request.user.pk%}
        {% if orders %}
            <h2>The user {% firstof user.first_name user.username %} has completed the following orders </h2>
            {% cache 120 owner user.pk %}
                <div>
                    {% for order in orders %}
                        <div>
                            <p>
                                <a href="{% url 'shopapp:order_detail' pk=order.pk   %}">
                                    Order : {{ order.pk }}
                                </a>
                            </p>
                            <p>Promocode:  <code>{{ order.promocode}}</code></p>
                            <p>Delivery address: {{ order.delivery_address}}</p>
                            <div>
                                Products in order:
                                <ul>
                                    {% for product in order.products.all %}
                                        <li>{{ product.name }} for ${{ product.price }}</li>
                                    {% endfor%}
                                </ul>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% endcache %}
        {% else %}
            <h3>The user  {% firstof user.first_name user.username %} doesn't have any orders yet</h3>
        {% endif %}
    {% endif %}


{% endblock %}

mysite/shopapp/templates/shopapp/product-details.html
{% extends 'shopapp/base.html'%}
{% load i18n %}

{% block title %}
   {% translate  'Product detail' %}
{% endblock %}


{% block body %}
    <h1>{% translate  'Name' context 'product name' %}: <strong>{{ product.name }}</strong></h1>
    <div>
        <div>{% translate  'Description' %}: <em>{{ product.description }}</em></div>
        <div>{% translate  'Price' %}: {{ product.price }}</div>
        <div>{% translate  'Discount' %}: {{ product.discount }}</div>
        <div>{% translate  'Archived' %}: {{ product.archived }}</div>
        <div>{% translate  'Created_by' %}: {{ product.created_by.username }} id:{{ product.created_by.pk }}</div>
        {% if product.preview %}
          <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
        {% endif %}

        <h3>{% translate  'Gallery' %}:</h3>
        {% with product.images.all as img_product %}
        {% blocktranslate count img_count=img_product|length %}
            one image has been uploaded
            {% plural %}
            {{ img_count }} images uploaded
        {% endblocktranslate %}

        <div>
            {% for img in img_product %}
                <div>
                    <img src="{{ img.image.url }}" alt="{{ img.image.name }}">
                </div>
            {% endfor %}
        </div>

    </div>


    <div>
        <a href="{% url 'shopapp:products_list' %}">{% translate  'Back To Products list' %}</a>
    </div>

    {% if "shopapp.change_product" in perms %}
        {% if product.created_by.pk == user.pk or user.is_superuser %}
            <div>
                <a href="{% url 'shopapp:product_update' pk=product.pk %}">{% translate  'Update product' %}</a>
            </div>
        {% endif %}
    {% endif %}


    <div>
        <a href="{% url 'shopapp:product_delete' pk=product.pk %}">{% translate  'Delete product' %}</a>
    </div>
{% endwith %}
{% endblock %}

mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html'%}

{% block title %}
  Delete product {{ object.name }}
{% endblock %}


{% block body %}
  <h1>Delete product {{ object.name }}</h1>
  <br>
  <div>
    <a href="{% url 'shopapp:product_detail' pk=object.pk %}"> Back to product </a>
  </div>
  <br>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Delete</button>
    </form>
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html'%}

{% block title %}
  Creeate product
{% endblock %}


{% block body %}
  <h1>Create new product from form</h1>
  <div>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p}}
      <button type="submit">Create</button>
    </form>
  </div>

<div>
    <a href="{% url 'shopapp:products_list' %}"> Back to products list </a>
  </div>

{% endblock %}

mysite/shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html'%}

{% block title %}
  Product List
{% endblock %}

{% block body %}
  <h1>Products</h1>
  {% if products %}
    <div>
      {% for product in products %}
        <div>
          <p><a href="{% url 'shopapp:product_detail' pk=product.pk %}">Name: {{ product.name }}</a></p>
          <p>Price: {{ product.price }}</p>
          <p>Discount: {% firstof product.discount 'no discount' %}</p>
        </div>

        {% if product.preview %}
          <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
        {% endif %}

      {% endfor %}
    </div>
  {% else %}
    <h3>No products yet</h3>
  {% endif %}


  {% if "shopapp.add_product" in perms %}
    <div>
      <a href="{% url 'shopapp:product_create' %}"> Create a new product </a>
    </div>
  {% endif %}

{% endblock%}

mysite/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html'%}

{% block title %}
  Shop Index
{% endblock %}


{% block body %}
  <h1>Hello Shop Index!</h1>

  <div>
    <ul>
      {% for name, price in products %}
        <li>{{ name|lower }} {{ name|length|add:"2" }} for ${{ price }}</li>
        {% if name|length == 7 %}
          <span>Lucky product</span>
        {% endif %}
        {% empty %}
            No products her
      {% endfor %}
    </ul>
  </div>

  <div>
    Time Running : {{ time_running }}
  </div>

  <div>
    {% lorem 3 p random %}
  </div>
{% endblock %}