mysite/myauth/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from .views import (MyLogoutView,
                    set_cookie_view,
                    get_cookie_view,
                    set_session_view,
                    get_session_view,
                    AboutMeViews,
                    RegisterView,
                    ChangeAvatarUser,
                    UserListView,
                    UserDetailView,
                    UserUpdate,
                    )

app_name = 'myauth'

urlpatterns = [
    path(
        'login/',
        LoginView.as_view(
            template_name="myauth/login.html",
            redirect_authenticated_user=True,
        ),
        name='login'
    ),
    path("logout/", MyLogoutView.as_view(), name="logout"),
    path("cookie/get/", get_cookie_view, name="cookie-get"),
    path("cookie/set/", set_cookie_view, name="cookie-set"),
    path("session/get/", get_session_view, name="session-get"),
    path("session/set/", set_session_view, name="session-set"),
    path("about-me/", AboutMeViews.as_view(), name="about-me"),
    path("register/", RegisterView.as_view(), name="register"),
    path("users/", UserListView.as_view(), name="users-list"),
    path("users/<int:pk>/", UserDetailView.as_view(), name="users-detail"),
    path("change_avatar/<int:pk>/", ChangeAvatarUser.as_view(), name="change-avatar"),

    path("users/update/<int:pk>/", UserUpdate.as_view(), name="users-update"),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from django.contrib.sitemaps.views import sitemap

from .sitemaps import sitemaps

urlpatterns = [
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),

    path('req/', include('requestdataapp.urls')),
    path('accounts/', include('myauth.urls')),
    path('blog/', include('blogapp.urls')),
    path(
        'sitemap.xml',
        sitemap,
        {"sitemaps": sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    )
]

urlpatterns += i18n_patterns(
path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('shop/', include('shopapp.urls')),
)


if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls"))
    )

mysite/myauth/models.py
from django.db import models
from django.contrib.auth.models import User


def avatar_directory_path(instance: "Profile", filename: str) -> str:
    return f"users/user_{instance.pk}/avatar/{filename}"


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500,  blank=True)
    agreement_accepted = models.BooleanField(default=False)
    avatar = models.ImageField(null=True, blank=True, upload_to=avatar_directory_path)

mysite/myauth/forms.py
from django import  forms


from .models import Profile


class AvatarChange(forms.ModelForm):
    """ Форма смены аватарки пользователя """
    class Meta:
        model = Profile
        fields = 'avatar',

mysite/myauth/views.py
from django.http import HttpRequest, HttpResponse, HttpResponseForbidden
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View, TemplateView, CreateView, UpdateView, ListView, DetailView
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


from .models import Profile
from .forms import AvatarChange

class MyLogoutView(View):

    def get(self, request):
        logout(request)
        return redirect('myauth:login')


class AboutMeViews(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Profile
    template_name = 'myauth/about-me.html'

    def get_object(self, queryset=None):
        return self.request.user.profile

    def test_func(self):
        return self.request.user == self.get_object().user



class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = "myauth/register.html"
    success_url = reverse_lazy("myauth:about-me")

    def form_valid(self, form):
        respose = super().form_valid(form)
        Profile.objects.create(user=self.object)
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")
        user = authenticate(request=self.request, username=username, password=password)
        login(self.request, user)
        return respose


def set_cookie_view(request: HttpRequest) -> HttpResponse:
    response = HttpResponse("Cookie set")
    response.set_cookie("fizz", "buzz", max_age=3600)
    return response


def get_cookie_view(request: HttpRequest) -> HttpResponse:
    value = request.COOKIES.get("fizz", "default value")
    return HttpResponse(f"Cookie value {value!r}")

def set_session_view(request: HttpRequest) -> HttpResponse:
    request.session["foobar"] = "spameggs"
    return HttpResponse("Session Set")

def get_session_view(request: HttpRequest) -> HttpResponse:
    value = request.session.get("foobar", "default value")
    return HttpResponse(f"Session value {value!r}")

class ChangeAvatarUser(UpdateView):
    """Смена аватарки пользователем со страницы about-me"""
    model = Profile
    form_class = AvatarChange
    template_name = "myauth/profile_change_avatar.html"

    def get_success_url(self):
        return reverse("myauth:about-me")

class UserListView(ListView):
    """Класс отображение списка пользователей"""
    model = User
    template_name = 'myauth/users-list.html'
    context_object_name = 'users'


class UserDetailView(DetailView):
    """Класс просмотра пользователя"""
    template_name = 'myauth/user-detail.html'
    queryset = User.objects.select_related('profile')
    context_object_name = 'user'



class UserUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """Класс изменения пользователя"""

    model = Profile
    form_class = AvatarChange
    template_name = "myauth/profile_change_avatar.html"

    def test_func(self):
        """редактирровать могут админы, суперпользователи и хозяин аккаунта"""
        return (self.request.user.is_superuser or
                self.request.user.is_staff or
                self.request.user == self.get_object().user)

    def get_success_url(self):
        return reverse('myauth:users-detail', kwargs={'pk': self.object.user.pk})

mysite/myauth/templates/myauth/about-me.html
{% extends 'myauth/base.html'%}

{% block title %}
    User info
{% endblock %}


{% block body %}
  <h1>User info</h1>
  {% if user.is_authenticated %}
    <h2>Detail</h2>
    <p>Username: {{ user.username }}</p>

    <div>
      {% if user.profile.avatar %}
        <img src="{{ user.profile.avatar.url }}" alt="{{ user.profile.avatar.name }}">
      {% else %}
        No avatar
      {% endif %}
    </div>

    <p>Firstname: {{ user.first_name }}</p>
    <p>Lastname: {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>
    <p>Bio: {{ user.profile.bio }}</p>
    <a href="{% url 'myauth:change-avatar' pk=user.profile.pk %}">Change avatar: {{ user.username }}</a>
  {% else %}
    <h2>User is anonymous</h2>
  {% endif %}
{% endblock %}

mysite/myauth/templates/myauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
      {% block title %}
        Base Title
      {% endblock %}
    </title>
</head>
<body>
  {% block body %}
    Base Body
  {% endblock %}

</body>
</html>

mysite/myauth/templates/myauth/login.html
{% extends 'myauth/base.html'%}

{% block title %}
    Ligin
{% endblock %}


{% block body %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
{% endblock %}

mysite/myauth/templates/myauth/profile_change_avatar.html
{% extends 'myauth/base.html'%}

{% block title %}
    Change avatar
{% endblock %}


{% block body %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Change</button>
    </form>
{% endblock %}

mysite/myauth/templates/myauth/register.html
{% extends 'myauth/base.html'%}

{% block title %}
    Register new user
{% endblock %}

{% block body %}
    <h1>Register</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit"  value="Register">
    </form>
{% endblock %}

mysite/myauth/templates/myauth/user-detail.html
{% extends 'myauth/base.html'%}

{% block title %}
    User info
{% endblock %}


{% block body %}
  <h1>User {{ user.username }}</h1>

  <div>
    {% if user.profile.avatar %}
      <img src="{{ user.profile.avatar.url }}" alt="{{ user.profile.avatar.name }}">
    {% else %}
      No avatar
    {% endif %}
  </div>

  <p>Firstname: {{ user.first_name }}</p>
  <p>Lastname: {{ user.last_name }}</p>
  <p>ID: {{ user.pk }}</p>
  <p>ID Profile: {{ user.profile.pk }}</p>
  <p>Email: {{ user.email }}</p>
  <p>Bio: {{ user.profile.bio }}</p>
  <p>Admin: {{ user.is_staff }}</p>
  <p>Superuser: {{ user.is_superuser }}</p>

  {% if request.user.is_staff or request.user.is_superuser or user.pk == request.user.pk%}
    <div>
      <a href="{% url 'myauth:users-update' pk=user.profile.pk  %}">Update avatar</a>
    </div>
  {% endif %}

  <div>
    <a href="{% url 'myauth:users-list' %}">Back To Users list</a>
  </div>

{% endblock %}

mysite/myauth/templates/myauth/users-list.html
{% extends 'myauth/base.html'%}

{% block title %}
    Users List
{% endblock %}


{% block body %}
  <h1>Users</h1>

  {% for user in users %}
    <div>

      <p>
        User:
        <a href="{% url 'myauth:users-detail' pk=user.pk   %}">
          {% firstof user.first_name user.username %}
        </a>
      </p>
      <p>ID: {{ user.pk }}</p>
      <p>Email: {% firstof user.email  "No email" %}</p>
      <hr>
    </div>
  {% endfor %}


{% endblock %}